# Generated by Django 4.2 on 2023-04-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance_system', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'STUDENT'), (1, 'HOD'), (2, 'STAFF')], default=1, max_length=1),
        ),
    ]
