# Generated by Django 4.2 on 2023-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance_system', '0004_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(upload_to='static/assets/img/profile_pic/'),
        ),
    ]
