# Generated by Django 4.2 on 2023-04-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance_system', '0008_alter_customuser_user_type_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'STUDENT'), (2, 'STAFF'), (1, 'HOD')], default=1, max_length=1),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_attendance_system.cource')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_attendance_system.staff')),
            ],
        ),
    ]
