# Generated by Django 4.2 on 2023-04-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance_system', '0012_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'STUDENT'), (2, 'STAFF'), (1, 'HOD')], default=1, max_length=1),
        ),
    ]
