# Generated by Django 4.2 on 2023-04-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance_system', '0017_alter_customuser_user_type_student_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (3, 'STUDENT'), (1, 'HOD')], default=1, max_length=1),
        ),
    ]
