# Generated by Django 4.2 on 2023-04-27 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance_system', '0022_rename_attenance_date_attendance_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='attendance_report',
            name='student_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app_attendance_system.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (1, 'HOD'), (3, 'STUDENT')], default=1, max_length=1),
        ),
    ]
