# Generated by Django 4.2 on 2023-04-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance_system', '0023_remove_attendance_report_subject_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_report',
            old_name='attendace_id',
            new_name='attendance_id',
        ),
    ]
